### ISSUE TITLE
Update k6 install instruction

### ISSUE THREAD

**Issue by robingustafsson** [avivasolutionsnl/Pensum-runner#11]
Hey @joostmeijles, awesome project!

The k6 install instructions at https://github.com/avivasolutionsnl/Pensum-runner#install should be updated though, `npm install k6` won't work unfortunately. We've still not decided what to do with the [k6 npm package](https://www.npmjs.com/package/k6/) 😅 ...but we realize the existance of the (empty) package is misleading to say the least.

See the available installation options at https://k6.io/docs/getting-started/installation.

**Comment by joostmeijles** [comment]
@robingustafsson fixed, thanks for noticing! 

Since when is the k6 npm package empty? 😁

**Comment by robingustafsson** [comment]
I don't think we ever put anything in it actually 😅 We had lots of debate internally on whether it would do more harm than good as it might signal that k6 is node compatible, or even based on node, which it isn't. The current plan is to add something to the package so it at least prints a friendly message pointing to the installation instructions in the docs or similar.
